### ISSUE TITLE
every bpm is 146

### ISSUE THREAD

**Issue by zachfagerness** [monstercat/bpm.js#2]
every song I scan

**Comment by jb55** [comment]
figure it out? from our tests bpm.js isn't super accurate all the time :(

**Comment by zachfagerness** [comment]
I was having some trouble getting sox to work so it was piping nothing, mine weren't super accurate until I upped the rate to 96000. But now they seem accurate it's kind of hard to tell ya know because how do you know a google search bpm is right lol.

I'm just happy I dont have to do it on the client side anymore with my npm module waveform-bpm
