### ISSUE TITLE
Lock dev dependencies

### ISSUE THREAD

**Issue by roccomuso** [monstercat/bpm.js#6]
Lock dev dependencies.

Using `*` is a bad practice.
Tests are failing indeed.

**Comment by jb55** [comment]
The tests seem to be running on very old versions of node as well...

**Comment by roccomuso** [comment]
Yep. It's worth upgrading it.

**Comment by jb55** [comment]
build passing after upgrading node versions, I'm not too concerned about locking mocha and expect dev deps tbh.
